version: '1.0'

services:
  discord-bot:
    build:
      context: .
    container_name: discord_bot
    restart: always
    env_file: .env
    volumes:
      - .:/app
    command: python run.py